eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

server:
  port: 10001

spring:
  application:
    name: seller
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ru.nobler.me:3306/qunar_seller
    username: developer
    password: cuiyicong